model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['nuscenes_reid']
  targets: ['nuscenes_reid']
  combineall: False
  transforms: ['random_flip']
  save_dir: 'deep-person-reid/log/osnet_x1_0_nuscenes_tripplet_cosinelr'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    weight_x: 0.5
    weight_t: 0.5

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False